spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST}:5432/trade_platform
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    format_sql: true
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect

trade:
  platform:
    security:
      secret: ${SECRET}

via-cep:
    url: "https://viacep.com.br/ws/"